module.exports = {
    cookieSecret: 'nbme',
    connectionUrl: 'mongodb://localhost/nbme',

    dev: true,
    js: [
        'bower/jquery/jquery.js',
        'bower/underscore/underscore.js',
        'bower/handlebars/handlebars.js',
        'bower/ember/ember.js',
        'bower/ember-data-shim/ember-data.js',
        'bower/ember-auth/dist/ember-auth.js',
        'bower/ember-simple-auth/ember-simple-auth.js',
        'lib/ember-mongo-adapter/mongo-adapter.js',

        'lib/metronic/plugins/jquery-migrate-1.2.1.min.js',
        'lib/metronic/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js',
        'lib/metronic/plugins/bootstrap/js/bootstrap.min.js',
        'lib/metronic/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js',
        'lib/metronic/plugins/jquery-slimscroll/jquery.slimscroll.min.js',
        'lib/metronic/plugins/jquery.blockui.min.js',
        'lib/metronic/plugins/jquery.cookie.min.js',
        'lib/metronic/plugins/uniform/jquery.uniform.min.js',
        'lib/metronic/plugins/jquery-validation/dist/jquery.validate.min.js',
        'lib/metronic/plugins/select2/select2.min.js',
        'lib/metronic/plugins/jqvmap/jqvmap/jquery.vmap.js',
        'lib/metronic/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js',
        'lib/metronic/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js',
        'lib/metronic/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js',
        'lib/metronic/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js',
        'lib/metronic/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js',
        'lib/metronic/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js',
        'lib/metronic/plugins/flot/jquery.flot.js',
        'lib/metronic/plugins/flot/jquery.flot.resize.js',
        'lib/metronic/plugins/jquery.pulsate.min.js',
        'lib/metronic/plugins/bootstrap-daterangepicker/moment.min.js',
        'lib/metronic/plugins/bootstrap-daterangepicker/daterangepicker.js',
        'lib/metronic/plugins/gritter/js/jquery.gritter.js',
        'lib/metronic/plugins/fullcalendar/fullcalendar/fullcalendar.min.js',
        'lib/metronic/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js',
        'lib/metronic/plugins/jquery.sparkline.min.js',
        'lib/metronic/scripts/app.js',
        'lib/metronic/scripts/login.js',
        'app.js'
    ],
    css: [
        'fonts/font.css',
        'lib/metronic/plugins/font-awesome/css/font-awesome.min.css',
        'lib/metronic/plugins/bootstrap/css/bootstrap.min.css',
        'lib/metronic/plugins/uniform/css/uniform.default.css',
        'lib/metronic/plugins/gritter/css/jquery.gritter.css',
        'lib/metronic/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css',
        'lib/metronic/plugins/fullcalendar/fullcalendar/fullcalendar.css',
        'lib/metronic/plugins/jqvmap/jqvmap/jqvmap.css',
        'lib/metronic/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css',
        'lib/metronic/plugins/font-awesome/css/font-awesome.min.css',
        'lib/metronic/plugins/select2/select2_metro.css',
        'lib/metronic/css/style-metronic.css',
        'lib/metronic/css/style.css',
        'lib/metronic/css/style-responsive.css',
        'lib/metronic/css/plugins.css',
        'lib/metronic/css/pages/tasks.css',
        'lib/metronic/css/pages/login.css',
        'lib/metronic/css/pages/lock.css'
    ]
};

